--[[
================================================================================
                                    LICENSE                                     
================================================================================

MIT License

Copyright (c) 2026 NoName-wks

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.NECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

--------------------------------------------------------------------------------
[안내] 아래의 내용은 영문 라이선스의 이해를 돕기 위한 한국어 번역본입니다.
법적 효력은 오직 위의 영문 원본(Standard English Text)에만 발생합니다.
--------------------------------------------------------------------------------
MIT 라이선스 (MIT License)

Copyright (c) 2026 NoName-wks

이하의 권한은 본 소프트웨어 및 관련 문서 파일(이하 "소프트웨어")의 사본을 얻는 
모든 사람에게 무료로 제공되며, 본 소프트웨어를 취급함에 있어 제한 없이 권리를 
사용할 수 있습니다. 여기에는 소프트웨어의 사본을 제한 없이 사용, 복제, 수정, 
합병, 출판, 배포, 서브라이선스 부여 및/또는 판매할 권리와 본 소프트웨어를 
제공받은 사람에게 그러한 행위를 허용하는 권리가 포함되지만, 이에 국한되지는 않습니다.

위에 명시된 저작권 고지 및 본 허가 고지는 소프트웨어의 모든 사본 또는 중요한 
부분에 포함되어야 합니다.

소프트웨어는 "있는 그대로" 제공되며, 상품성, 특정 목적에 대한 적합성 및 
비침해에 대한 보증을 포함하여(단, 이에 국한되지 않음) 명시적이거나 묵시적인 
어떠한 형태의 보증도 하지 않습니다. 어떠한 경우에도 저작자나 저작권자는 계약, 
불법 행위 또는 다른 방식으로 발생했든 간에, 소프트웨어, 사용 또는 다른 취급과 
관련하여 발생하는 계약, 불법 행위 또는 다른 청구, 손해 또는 기타 책임에 대해 
책임을 지지 않습니다.
================================================================================
]]

--[[ README
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
]]
